# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt6 UI code generator 6.10.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(397, 290)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.submit_vote_button = QtWidgets.QPushButton(parent=self.centralwidget)
        self.submit_vote_button.setGeometry(QtCore.QRect(140, 170, 113, 32))
        self.submit_vote_button.setObjectName("submit_vote_button")
        self.voter_id_input = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.voter_id_input.setGeometry(QtCore.QRect(140, 40, 131, 21))
        self.voter_id_input.setObjectName("voter_id_input")
        self.candidate_1_radio_button = QtWidgets.QRadioButton(parent=self.centralwidget)
        self.candidate_1_radio_button.setGeometry(QtCore.QRect(160, 110, 100, 20))
        font = QtGui.QFont()
        font.setFamily("Cochin")
        font.setPointSize(14)
        self.candidate_1_radio_button.setFont(font)
        self.candidate_1_radio_button.setObjectName("candidate_1_radio_button")
        self.candidate_2_radio_button = QtWidgets.QRadioButton(parent=self.centralwidget)
        self.candidate_2_radio_button.setGeometry(QtCore.QRect(160, 140, 100, 20))
        font = QtGui.QFont()
        font.setFamily("Cochin")
        font.setPointSize(14)
        self.candidate_2_radio_button.setFont(font)
        self.candidate_2_radio_button.setObjectName("candidate_1_radio_button_2")
        self.id_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.id_label.setGeometry(QtCore.QRect(120, 40, 21, 20))
        self.id_label.setObjectName("id_label")
        self.voting_app_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.voting_app_label.setGeometry(QtCore.QRect(120, 10, 151, 21))
        font = QtGui.QFont()
        font.setFamily("Cochin")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.voting_app_label.setFont(font)
        self.voting_app_label.setObjectName("voting_app_label")
        self.candidates_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.candidates_label.setGeometry(QtCore.QRect(150, 80, 91, 16))
        font = QtGui.QFont()
        font.setFamily("Cochin")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.candidates_label.setFont(font)
        self.candidates_label.setObjectName("candidates_label")
        self.validation_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.validation_label.setGeometry(QtCore.QRect(70, 210, 250, 20))
        self.validation_label.setText("")
        self.validation_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.validation_label.setObjectName("validation_label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "My voting app"))
        self.submit_vote_button.setText(_translate("MainWindow", "Submit Vote"))
        self.candidate_1_radio_button.setText(_translate("MainWindow", "Jane"))
        self.candidate_2_radio_button.setText(_translate("MainWindow", "Jhon"))
        self.id_label.setText(_translate("MainWindow", "ID: "))
        self.voting_app_label.setText(_translate("MainWindow", "Voting Application"))
        self.candidates_label.setText(_translate("MainWindow", "Candidates"))

    



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
